### ISSUE TITLE
[BUG] Unexpected link behavior in to-do items.

### ISSUE THREAD

**Issue by ahmetcelikezer** [atolye15/checklist#60]
# Prerequisites

Please make sure you've checked the following to-do's.

- [x] My ad-block or script blocker is disabled
- [x] My browser is not IE
- [x] There are no browser extensions that may affect the issue on the browser
- [x] This is not a duplicated issue, I checked the current issues before creating this issue

# Current Behavior

When I click any link in a to-do item, that item marked to check right before the redirect to the link target.

# Expected Behavior

When I click any link in the to-do item, that item should not be marked as checked, it just should redirect to the link target.

# Failure Information

Please refer to the following steps for us to better understand the issue you are having.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. I visit the [this](https://checklist.atolye15.com/checklist/checklist-checklist) checklist page.
2. I clicked the link in the first item.
3. The to-do item marked as checked (not expected)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Browser: *Brave*
- Browser Version: *1.4.96*

**Comment by EricMcRay** [comment]
I think link should be opened in new window so adding `target` to links would be nice.

Beside of the link issue, also adding`ugc` value for `rel` attribute should be considered for SEO. Ref: https://support.google.com/webmasters/answer/96569?hl=tr
